# Generated by Django 4.1.5 on 2023-01-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('adoptante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Adoptante', to='pets_app.adoptante')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Animal', to='pets_app.animal')),
                ('voluntario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Voluntario', to='pets_app.voluntario')),
            ],
        ),
    ]
