# Generated by Django 4.1.5 on 2023-01-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0004_alter_adopcion_adoptante_alter_adopcion_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.URLField(default='https://static.guiaongs.org/wp-content/uploads/2016/07/Adopta.jpg'),
        ),
    ]
